<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_List_proxy" Id="{25f9644b-cf0d-4689-a359-654bae1caa32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_List_proxy EXTENDS TcBase.FB_List
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>