<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Observer_LREAL_" Id="{b8192a2c-e2e7-4cdb-9005-1d4ba8a7cd61}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Observer_LREAL_ EXTENDS TcBase.FB_Observer_LREAL
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="nUpdateCounter" Id="{0a2114c8-39b2-4fb4-88dc-6d5a6f2b8382}">
      <Declaration><![CDATA[PROPERTY nUpdateCounter : UDINT]]></Declaration>
      <Get Name="Get" Id="{c1db33dc-503c-495b-8bf7-fad580576830}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[nUpdateCounter := THIS^._nUpdateCounter;
]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>