<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_State" Id="{78f523dd-b10e-48af-9696-be0082d49d72}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_State EXTENDS FB_Object IMPLEMENTS I_State
VAR
    _bQueryRes:             BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="OnEntry" Id="{4827bf9d-4efc-4534-b327-d8caa3685450}">
      <Declaration><![CDATA[METHOD OnEntry
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnExit" Id="{75371a96-da45-4aac-8255-1aa82ef7ac67}">
      <Declaration><![CDATA[METHOD OnExit
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>