<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TestObject" Id="{578513b7-8eb5-4b09-9ef8-d1a89742a507}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestObject EXTENDS FB_Object
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _nTest: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="nTest" Id="{a6ad0285-11ba-4447-8e13-ec96833e2cfc}">
      <Declaration><![CDATA[PROPERTY nTest : INT]]></Declaration>
      <Get Name="Get" Id="{8d4a4ec0-c987-40c5-90fa-89d52487441e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[nTest := THIS^._nTest;
]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{ffa5d75b-9dc8-4f5b-8520-f4eabd3d5234}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[THIS^._nTest := nTest;
]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>