<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_State4" Id="{a7ebef2c-19a5-4130-90b6-f36862d2a4c2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_State4 EXTENDS FB_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>