<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_State1" Id="{915978e7-92ee-4f02-a74f-b5db3f8bd174}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_State1 EXTENDS FB_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>