on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: [self-hosted, Windows, x64, runner-1]
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create artifacts
        run: .\tools\createArtifacts.ps1

      - name: Install GitHub CLI
        run: |
          choco install gh -y
          refreshenv

      - name: Create Release
        run: gh release create ${{ github.ref }} (Get-Item ./tools/*.library) --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
