on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  create-artifacts:
    name: Publish to npm
    runs-on: [self-hosted, Windows, x64]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create artifacts
        run: .\tools\createArtifacts.ps1

  create-github-release:
    name: Create GitHub Release
    runs-on: [self-hosted, Windows, x64]
    needs: create-artifacts
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
